---
#-------------------------------
# General Site Settings

title: Mario Roos
logo:
author: Mario
description: this is meta description
email: marioroos2502@gmail.com

menu:
  - { name: About, link: "/about" }
  - { name: Experience, link: "/experience" }
  - { name: Publications, link: "/publications" }


  # - { name: Blog, link: "/blog" }
#  - { name: Portfolio, link: "/portfolio" }
  # - { name: Contact, link: "/contact" }



#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Mario <br> Software engineer </br>

social:
  - { icon: "ti-github", link: "https://github.com/mariorht" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/marioroos/" }
 # - { icon: "ti-strava", link: "https://www.strava.com/athletes/116477197" }

#-------------------------------
# About (Section and Page)

# About SectionLorem
blurb: I am Mario Roos Hoefgeest Toribio, a passionate and experienced C++ Software Engineer specialized in computer vision and industrial inspection. Currently pursuing a Ph.D. in 3D inspection systems for large-scale and intricate geometries.
blurb-btn-name: know more
blurb-btn-link: /about

# About Page



#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - name: Programming
    color: "#9473e6"
    value: "85%"
    details:
      - "C++"
      - "Python"
      - "Golang"
      - "Databases: PostgreSQL, SQLite"
      - "Multithreading"
      - "Multiplatform development: Linux, Windows"

  - name: C++
    color: "#fdb157"
    value: "90%"
    details:
      - "Qt"
      - "OpenCV"
      - "OpenGL, OpenCascade"
      - "CUDA"
      - "Build systems: CMake, QMake"

  - name: Python
    color: "#9473e6"
    value: "65%"
    details:
      - "Data science: Pandas, NumPy, SKLearn."
      - "Computer vision: OpenCV"
      - "Web: Flask, FastApi"

  - name: Computer vision
    color: "#1dd1a1"
    value: "80%"
    details:
      - "Image processing"
      - "Object detection"
      - "3D vision"

  - name: Linux
    color: "#bdecf6"
    value: "80%"
    details:
      - "Git"
      - "CI/CD: Docker, Jenkins"
      - "System administration"
      - "Shell scripting"

  - name: Web
    color: "#ff9f43"
    value: "50%"
    details:
      - "HTML, CSS, JavaScript"
      - "Flask, FastApi"



#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: "Software Lead",
      icon: "icon-1.png",
      date: "2023 - Present",
      organization: "CIN ADVANCED SYSTEMS GROUP S.L.",
      location: "Gijón, Spain",
      details: [
        "Led software development for industrial inspection projects, defining and implementing efficient workflows.",
        "Standardized and simplified development environments through containerization (Docker).",
        "Established CI/CD practices using GitLab and GitLab Runners, enabling efficient integration and deployment pipelines for C++ and Python projects.",
        "Improved development processes, achieving faster and more reliable project implementation."
      ],
      tech_stack: [
        "Linux", "C++", "Python", "Docker", "CI/CD", "GitLab", "OpenCV", "Qt", "PostgreSQL", "CUDA", "Jenkins"
      ]
    }
  - {
      name: "Product Owner",
      icon: "icon-2.png",
      date: "2021 - 2022",
      organization: "CIN ADVANCED SYSTEMS GROUP S.L.",
      location: "Gijón, Spain",
      details: [
        "Developed distributed inspection systems integrating laser triangulation sensors, industrial robots, and motion systems for real-time automotive production inspection.",
        "Designed and implemented processes for detailed scanning, advanced data processing, and visualization, ensuring accuracy and reliability in defect detection."
      ],
      tech_stack: [
        "Linux", "Qt", "OpenCV", "C++", "Multithreading", "3D Visualization", "Agile methodologies", "Kanban"
      ]
    }
  - {
      name: "Computer Vision Engineer",
      icon: "icon-3.png",
      date: "2018 - 2021",
      organization: "CIN ADVANCED SYSTEMS GROUP S.L.",
      location: "Gijón, Spain",
      details: [
        "Integrated conoscopic holography sensors into mobile systems, ensuring real-time synchronization of scans and positions using SoC Zynq platforms with FPGA.",
        "Developed defect detection systems utilizing laser triangulation sensors."
      ],
      tech_stack: [
        "Linux", "C++", "Python", "FPGA", "Embedded Systems", "OpenCV", "Signal Processing"
      ]
    }
  - {
      name: "Research Intern",
      icon: "icon-1.png",
      date: "2017-2017",
      organization: "Escuela Politécnica de Ingeniería de Gijón",
      location: "Gijón, Spain",
      details: [
        "Designed a PCB for analog/digital interface and developed a three-phase power converter.",
        "Participated in a project simulating energy storage systems in collaboration with ArcelorMittal España."
      ],
      tech_stack: [
        "PCB Design", "Power Electronics", "Data Analysis"
      ]
  }

#-------------------------------
# Education Section

education-title: Academic
education:
  - {
      name: Ph.D. in Energy and Process Control,
      date: "2019-Present",
      organization: "Escuela Politécnica de Ingeniería de Gijón",
      thesis: "3D Inspection Systems for Large-Scale Parts with Complex Geometries"
    }
  - {
      name: Master’s in Automation and Industrial Informatics,
      date: "2017-2019",
      organization: "Escuela Politécnica de Ingeniería de Gijón",
      thesis: "Master's Thesis: 3D Data Acquisition System Based on an SoC Embedded System for a Conopoint Sensor"
    }
  - {
      name: Bachelor’s in Industrial Electronic Engineering. Specialization in Robotics,
      date: "2013-2017",
      organization: "Escuela Politécnica de Ingeniería de Gijón",
      thesis: "Bachelor's Thesis: 3D Model Reconstruction Using Computer Vision Techniques"
    }


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/fastapi.jpeg"
    url: "https://github.com/mariorht/fastapi_template"
    name: "FastAPI Template"

  - image: "assets/images/portfolio/bike.png"
    url: "https://github.com/mariorht/montreal_bikes_ussage"
    name: "Montreal Bikes Usage"

  - image: "assets/images/portfolio/pdf.png"
    url: "https://github.com/mariorht/PDF_tools"
    name: "PDF Tools"

  - image: "assets/images/portfolio/juego-de-la-vida.png"
    url: "https://mariorht.github.io/El-juego-de-la-vida-P5Js/"
    name: "Game of Life"

# Link to GitHub for more projects
portfolio-home-github: "https://github.com/mariorht"

#-------------------------------
# Publications Section
publications-title: Publications
publications:
  - {
      year: "2023",
      title: "Simulation of Laser Profilometer Measurements in the Presence of Speckle Using Perlin Noise",
      journal: "MDPI Sensors, Sep. 2, 2023",
      link: "https://doi.org/10.3390/s23177624",
      authors: "Sara Roos-Hoefgeest, Mario Roos-Hoefgeest, Ignacio Alvarez, Rafael C. González",

    }
  - {
      year: "2019",
      title: "Master's Thesis: 3D Data Acquisition System Based on an SoC Embedded System for a Conopoint Sensor",
      journal: "Repositorio Institucional de la Universidad de Oviedo",
      link: "http://hdl.handle.net/10651/50424",
      authors: "Mario Roos-Hoefgeest Toribio",
    }
  - {
      year: "2017",
      title: "Bachelor's Thesis: 3D Model Reconstruction Using Computer Vision Techniques",
      journal: "Repositorio Institucional de la Universidad de Oviedo",
      link: "https://hdl.handle.net/10651/76269",
      authors: "Mario Roos-Hoefgeest Toribio",
    }

# Preprints Section
preprints-title: Preprints
preprints:
  - {
      year: "2024",
      title: "Reinforcement Learning Approach to Optimizing Profilometric Sensor Trajectories for Surface Inspection",
      journal: "Preprint, arXiv",
      link: "https://arxiv.org/abs/2409.03429",
      authors: "Sara Roos-Hoefgeest, Mario Roos-Hoefgeest, Ignacio Alvarez, Rafael C. González",
    }


# Portfolio Page
# portfolio-label:
#   - { title: "UI/UX Design", type: "design" }
#   - { title: "BRANDING", type: "branding" }
#   - { title: "ILLUSTRATION", type: "illustration" }

# portfolio-items:
#   - image: "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"

#   - image: "assets/images/portfolio/item-2.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"

#   - image: "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"

#   - image: "assets/images/portfolio/item-6.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "branding"

#   - image: "assets/images/portfolio/item-8.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"

#   - image: "assets/images/portfolio/item-5.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"

#   - image: "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"

#   - image: "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"

#   - image: "assets/images/portfolio/item-7.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"



#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: marioroos2502@gmail.com
